apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: nagp
  labels:
    app: api-service
spec:
  replicas: 4
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: manishnagarro/nagp-k8-api-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: nagp
spec:
  selector:
    app: api-service
  type: LoadBalancer
  ports:
    - targetPort: 3000
      port: 3000
      protocol: TCP

#Rolling Update Test: kubectl set image deployment/api-service api-service=manishnagarro/nagp-k8-api-service:v1