apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce # Because only one DB node will be accessing this
  hostPath:
    path: "/mysql-data"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # In order for this to be claimed by the PVC

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db
  namespace: nagp
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: mysql-db # Volume to claim
  storageClassName: "" # In order for PVC to claim the relevant PV
  resources:
    requests:
      storage: 100Mi

